### ISSUE TITLE
`exec: i3-msg '[class="Code"] focus' && code -r {path}` in config causes crash

### ISSUE THREAD

**Issue by derethil** [seanrcollings/venture#14]
```python
i3-msg: invalid option -- 'r'
Traceback (most recent call last):
  File "/home/jaren/.local/bin/venture", line 8, in <module>
    sys.exit(cli())
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/cli.py", line 49, in __call__
    return run(self, execute)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/cli.py", line 188, in run
    return command.run(command_node)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/command/command.py", line 148, in run
    value = self.execute(command_node)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/command/keyword_command.py", line 18, in execute
    return self.function(**args)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/utils.py", line 46, in decorator
    return_value = func(*args, **kwargs)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/command/helpers.py", line 140, in wrapper
    return function(*args, **kwargs, **command.hidden_args)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/cli.py", line 78, in __default
    self.default_action(**kwargs)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/command/command.py", line 52, in __call__
    return self.function(*args, **kwargs)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/utils.py", line 46, in decorator
    return_value = func(*args, **kwargs)
  File "/home/jaren/.local/lib/python3.9/site-packages/arc/command/helpers.py", line 140, in wrapper
    return function(*args, **kwargs, **command.hidden_args)
  File "/home/jaren/.local/lib/python3.9/site-packages/venture/__main__.py", line 56, in run
    execute(choice)
  File "/home/jaren/.local/lib/python3.9/site-packages/venture/__main__.py", line 35, in execute
    subprocess.run(command, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['i3-msg', '[class="Code"] focus', '&&', 'code', '-r', '/home/jaren/Development/Work/piserver']' returned non-zero exit status 1.
```

**Comment by seanrcollings** [comment]
Resolved with v1.3.0
